id: AA67BAB1B
title: 'Treasury of Supreme Blessings: A Guru Yoga'
type: translation
pechas:
- I6B7C368E
- I34A1EAF9
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:13:48.849763
  last_modified_at: 2023-01-04 12:13:48.849771
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I6B7C368E/1678: 48A4
  I34A1EAF9/8094: 48A4
